### ISSUE TITLE
Default password?

### ISSUE THREAD

**Issue by vladola** [hotio/qbittorrent#2]
Just installed this docker container, but the default `admin/adminadmin` did not work. What am I doing wrong?

**Comment by qubidt** [comment]
FYI for people with the same problem:

Reproduced this in firefox when i was accessing by `<IP>:PORT`. The browser stores a cookie (`sid`) when the request to `/login` is made but doesn't send it when the request is made to `/` again, so you just get the same login prompt. Not sure what the issue is here but I'm not really a webdev so :shrug:  

Weird thing was it works fine in a *different* profile of the same browser, so I feel like it's some weird interaction of my browser settings/extensions, but I haven't been able to figure it out.

It's working now when going thru my reverse proxy (traefik) w/ a proper domain name. so extra :shrug: lol

something about the `sameSite` attribute, maybe? idk

**Comment by mgoggin** [comment]
Could be the `SameSite` cookie value.

If you're running this container locally and just need to get into to configure things and you're not exposing this to the internet, you can edit your qBittorrent.conf and add the following line to bypass authentication for requests on your local subnet:

```
WebUI\AuthSubnetWhitelist=192.168.1.0/24
WebUI\AuthSubnetWhitelistEnabled=true
```

You'll want to replace `192.168.1.0/24` with whatever your local subnet is.
